basic:
  share_links:
    client: true
    type: list
    default: 'twitter|facebook|email|renren|wechat'
    allow_any: false
    choices:
     - twitter
     - facebook
     - email
     - renern
     - wechat
login:
  wechat_qrconnect_client_id333:
    default: ''
  wechat_qrconnect_client_secret:
    default: ''
